from io import StringIO

import pandas as pd

from mecon.tags import tagging


basic_tags_csv_str = """name,conditions_json,type,date_created
All,"[{""amount"": {""greater_equal"": 0}}, {""amount"": {""less_equal"": 0}}]",Built-in,2025-12-17 23:33:02
Zero amount,"[{""amount"": {""equal"": 0}}]",Built-in,2025-12-17 23:33:02
Money In,"[{""amount"": {""greater"": 0}}]",Built-in,2025-12-17 23:33:02
Money Out,"[{""amount"": {""less"": 0}}]",Built-in,2025-12-17 23:33:02
Weekend,"[{""datetime.day_of_week"": {""equal"": ""Saturday""}}, {""datetime.day_of_week"": {""equal"": ""Sunday""}}]",Built-in,2025-12-17 23:33:02
Weekday,"[{""datetime.day_of_week"": {""equal"": ""Monday""}}, {""datetime.day_of_week"": {""equal"": ""Tuesday""}}, {""datetime.day_of_week"": {""equal"": ""Wednesday""}}, {""datetime.day_of_week"": {""equal"": ""Thursday""}}, {""datetime.day_of_week"": {""equal"": ""Friday""}}]",Built-in,2025-12-17 23:33:02
Monday,"[{""datetime.day_of_week"": {""equal"": ""Monday""}}]",Built-in,2025-12-17 23:33:02
Tuesday,"[{""datetime.day_of_week"": {""equal"": ""Tuesday""}}]",Built-in,2025-12-17 23:33:02
Wednesday,"[{""datetime.day_of_week"": {""equal"": ""Wednesday""}}]",Built-in,2025-12-17 23:33:02
Thursday,"[{""datetime.day_of_week"": {""equal"": ""Thursday""}}]",Built-in,2025-12-17 23:33:02
Friday,"[{""datetime.day_of_week"": {""equal"": ""Friday""}}]",Built-in,2025-12-17 23:33:02
Saturday,"[{""datetime.day_of_week"": {""equal"": ""Saturday""}}]",Built-in,2025-12-17 23:33:02
Sunday,"[{""datetime.day_of_week"": {""equal"": ""Sunday""}}]",Built-in,2025-12-17 23:33:02
Morning,"[{""datetime.hour"": {""greater_equal"": 8, ""less"": 12}}]",Built-in,2025-12-17 23:33:02
Afternoon,"[{""datetime.hour"": {""greater_equal"": 12, ""less"": 20}}]",Built-in,2025-12-17 23:33:02
Night,"[{""datetime.hour"": {""greater_equal"": 20}}, {""datetime.hour"": {""less"": 8}}]",Built-in,2025-12-17 23:33:02
$,"[{""currency"": {""equal"": ""USD""}}]",Built-in,2025-12-17 23:33:02
£,"[{""currency"": {""equal"": ""GBP""}}]",Built-in,2025-12-17 23:33:02
€,"[{""currency"": {""equal"": ""EUR""}}]",Built-in,2025-12-17 23:33:02
Romanian Leu,"[{""currency"": {""equal"": ""RON""}}]",Built-in,2025-12-17 23:33:02
Hungarian Forint,"[{""currency"": {""equal"": ""HUF""}}]",Built-in,2025-12-17 23:33:02
Swiss Franc,"[{""currency"": {""equal"": ""CHF""}}]",Built-in,2025-12-17 23:33:02
Employment Salary,"[{""tags"": {""contains"": ""Salary""}}]",Built-in,2026-08-10 15:27:02
Income,"[{""tags.split_comma"": {""in_csv"": ""Employment  Salary""}}, {""tags.split_comma"": {""in_csv"": ""Cash Interest""}}]",Built-in,2026-08-10 15:27:02
Living costs,"[{""tags.split_comma"":{""in_csv"":""Super Market""}},{""tags.split_comma"":{""in_csv"":""Home Bills""}},{""tags.split_comma"":{""in_csv"":""Rent""}}]",2025-01-22 00:40:10,Custom
Investments,"[{""tags.split_comma"": {""in_csv"": ""Stocks and Shares""}}, {""tags.split_comma"": {""in_csv"": ""Cash Interest""}}]",Built-in,2026-08-10 15:27:02
Essentials,"[{""tags.split_comma"": {""in_csv"": ""Super Market""}}, {""tags.split_comma"": {""in_csv"": ""Rent""}}, {""tags.split_comma"": {""in_csv"": ""Home Bills""}}, {""tags.split_comma"": {""in_csv"": ""Commute""}}, {""tags.split_comma"": {""in_csv"": ""Food""}}]",Built-in,2026-09-09 15:27:02
"""
basic_tags_df = pd.read_csv(StringIO(basic_tags_csv_str))


editable_tags_csv_str = """name,conditions_json,date_created,type
Online payments,"[{""description.lower"":{""contains"":""paypal""}},{""tags"":{""contains"":""Online orders""}},{""tags"":{""contains"":""Flight tickets""}},{""tags"":{""contains"":""Accommodation""}}]",2025-01-22 00:40:10,Editable Built-in
Commute,"[{""tags.split_comma"":{""in_csv"":""TFL,BorisBike,LimeBike,Uber Taxi""}}]",2025-01-22 00:40:10,Editable Built-in
Flight tickets,"[{""description.lower"":{""contains"":""wizz air""}},{""description.lower"":{""contains"":""british airways""}},{""description.lower"":{""contains"":""ryanair""}},{""description.lower"":{""contains"":""kiwi.com""}},{""description.lower"":{""contains"":""easyjet""}},{""description.lower"":{""contains"":""sky express""}},{""description.lower"":{""contains"":""budgetair""}},{""description.lower"":{""contains"":""olympic""}},{ ""description.lower"": { ""contains"": ""wizzair"" } },{""description.lower"":{""contains"":""jet2""}}]",2025-01-22 00:40:10,Editable Built-in
Train tickets,"[{""description.lower"":{""contains"":""trainline""}},{""description.lower"":{""contains"":""stansted express""}}]",2025-01-22 00:40:10,Editable Built-in
Cash,"{""description.lower"":{""contains"":""cash""}}",2025-01-22 00:40:10,Editable Built-in
Tap,"[{""datetime.str"":{""greater"":""2023-01-10""},""amount"":{""less"":0.0},""tags"":{""contains"":""Monzo"",""not_contains"":[""Transfer"",""Online payments""]}}]",2025-01-22 00:40:10,Editable Built-in
My transfers,"[{""id"": {""not_contains"": ""TRD212d20250211t163510ap364274i7""}, ""description"": {""contains"": ""bank:TRD212, action: Deposit""}}, {""description.lower"": {""contains"": ""transfer""}}, {""description.lower"": {""contains"": [""dimitri"", ""kontzeda""]}, ""tags.split_comma"": {""in_csv"": ""Revolut,Monzo,HSBC""}}, {""description"": {""contains"": ""Top-Up by *0852""}, ""tags.split_comma"": {""in_csv"": ""Revolut""}}, {""description"": {""contains"": ""Payment from Kontzedaki""}, ""tags.split_comma"": {""in_csv"": ""Revolut""}}, {""description"": {""contains"": ""To Dimitrios Kontzedakis""}, ""tags.split_comma"": {""in_csv"": ""Revolut""}}, {""description"": {""contains"": ""Revolut**4562*""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description.upper"": {""contains"": ""MY REVO""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description"": {""contains"": ""DIMITRIS MONZO WEEKLY SO""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description"": {""contains"": ""DIMITRIOS KONTZEDA TO REVOLUT SO""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description"": {""contains"": ""Dimitrios Kontzeda Sent from Revolut CR""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description"": {""contains"": ""Dimitrios Kontzeda Sent from Monzo CR""}, ""tags.split_comma"": {""in_csv"": ""HSBC""}}, {""description.lower"": {""contains"": ""kontzedaki d""}, ""tags.split_comma"": {""in_csv"": ""Monzo""}}]",2025-01-22 00:40:10,Editable Built-in
Super Market,"[{""description.lower"": {""contains"": ""galaxias""}}, {""description.lower"": {""contains"": ""vasilopoulos""}}, {""description.lower"": {""contains"": ""masoutis""}}, {""description.lower"": {""contains"": ""supermercat""}}, {""description.lower"": {""contains"": ""supero""}}, {""description.lower"": {""contains"": ""superette""}}, {""description.lower"": {""contains"": ""supersave""}}, {""description.lower"": {""contains"": ""supermarket""}}, {""description.lower"": {""contains"": ""syn ka""}}, {""description.lower"": {""contains"": ""syn.ka""}}, {""description.lower"": {""contains"": ""sklavenitis""}}, {""description.lower"": {""contains"": ""elif food""}}, {""description.lower"": {""contains"": ""asda""}}, {""description.lower"": {""contains"": ""sainsbury"", ""not_contains"": ""cash sainsby""}}, {""description.lower"": {""contains"": ""tesco"", ""not_contains"": ""cash at tesco""}}, {""description.lower"": {""contains"": ""aldi""}}, {""description.lower"": {""contains"": ""ally""}}, {""description.lower"": {""contains"": ""lidl""}}, {""description.lower"": {""contains"": ""poundland""}}, {""description.lower"": {""contains"": ""co-op""}}, {""description.lower"": {""contains"": ""waitrose""}}, {""description.lower"": {""contains"": ""morrisons""}}, {""description.lower"": {""contains"": [""marks"", ""spencer""]}}, {""description.lower"": {""contains"": ""nisa""}}]",2025-01-22 00:40:10,Editable Built-in
Rent,"[{""amount"": {""less_equal"": -800}, ""description.lower"": {""contains"": ""grainger""}}, {""description"": {""contains"": ""Amanmeet Singh Bha rent BP""}}, {""description"": {""contains"": ""Dr Sina Motesharei""}}, {""description"": {""contains"": ""EDF""}}, {""description"": {""contains"": ""EDF ENERGY-ECOM PLYMOUTH VIS""}}, {""description"": {""contains"": ""INSTABOOK LTD""}}, {""id"": {""in"": ""TLREVOGBP-d20220810t190439-an57500-iMOCKd2f07fe5-f661-4d1f-bf71-7eebd34ba027,TLREVOGBP-d20220810t211424-an57500-iMOCK000db21a-b867-4bf9-aa7f-2401c54007ab,TLREVOGBP-d20220810t190500-an75000-iMOCK05ee323b-d662-4fc7-8697-464750ed199d,TLREVOGBP-d20230421t094803-an40000-iMOCK82cd34d0-64a4-4217-a36f-e8754dcdbb33,TLREVOGBP-d20230301t141958-an38000-iMOCKcf652e70-9989-41b8-96c6-850f3886e62c,TLREVOGBP-d20220810t190439-an57500-iMOCKd2f07fe5-f661-4d1f-bf71-7eebd34ba027,TLREVOGBP-d20200106t181345-an50000-iMOCKe0f21473-b0ca-48ec-80b7-e52e6a66213d,MonzoAPI-d20200203t133216-an40000-id.tx_00009rf6iRCr2zJCr2zTEH,TLREVOGBP-d20200203t132435-an25349-iMOCKef1c726f-3f9c-4543-b690-8890a1f8c457,TLREVOGBP-d20200203t140951-an10349-iMOCK1afd7d2d-a454-427d-b0e9-f303ce51e81e,MonzoAPI-d20200301t011821-an40000-id.tx_00009sY15bSTBTrWFgzFIH,MonzoAPI-d20200302t200328-an20000-id.tx_00009sbi0yOVMNPxgVKsFt,MonzoAPI-d20200302t200239-an10000-id.tx_00009sbhwQv1sYDESh6CFl,TLREVOGBP-d20200327t194415-an7000-iMOCK6fb0e5bf-e09e-43f6-b055-f3131125bc4b""}}, {""amount"": {""equal"": 450}, ""description.lower"": {""contains"": ""from georgios""}}, {""amount"": {""greater_equal"": 400}, ""description.lower"": {""contains"": ""eleni exarchou""}}, {""amount"": {""greater_equal"": 600}, ""description.lower"": {""contains"": ""from georgios""}}, {""amount"": {""greater_equal"": 400}, ""description.lower"": {""contains"": ""sideris""}}, {""amount"": {""equal"": 600}, ""description.lower"": {""contains"": ""from eleni exarchou""}}, {""amount"": {""equal"": 575}, ""description.lower"": {""contains"": ""from eleni exarchou""}}, {""amount"": {""equal"": 550}, ""description.lower"": {""contains"": ""from georgios""}}, {""amount"": {""equal"": 550}, ""description.lower"": {""contains"": ""from eleni exarchou""}}, {""amount"": {""equal"": 575}, ""description.lower"": {""contains"": ""from georgios""}}, {""description.lower"": {""contains"": ""joseph""}}, {""description.upper"": {""contains"": ""PEACHEY""}}, {""description.upper"": {""contains"": ""GRADY ALWYNE""}}, {""description.upper"": {""contains"": ""IGBONS""}}]",,Editable Built-in
Cash Interest,"[{""description.lower"": {""contains"": ""interest on cash""}}, {""description.lower"": {""contains"": ""added gross""}}, {""description.lower"": {""contains"": ""gross interest""}}]",,Editable Built-in
Savings,"[{""tags.split_comma"": {""in_csv"": ""Cash Interest""}, ""description.lower"": {""contains"": ""bank:ob-hsbc""}}, {""description.upper"": {""contains_phrase"": ""401100 68337632 INTERNET TRANSFER""}}]",,Editable Built-in
Stocks and Shares,"[{""description.lower"": {""contains"": [""bank:inveng"", ""purchase""]}},  {""description.lower"": {""contains"": [""bank:inveng"", ""sale""]}}, {""description.lower"": {""contains"": [""bank:trd212,"", ""ticker"", ""market buy""]}}, {""description.lower"": {""contains"": [""bank:trd212,"", ""ticker"", ""market sell""]}}]",,Editable Built-in
Subscriptions,"[ { ""description.lower"": { ""contains"": ""nord"" } }, { ""description.lower"": { ""contains"": ""mubi"" } }, { ""description.lower"": { ""contains"": ""netflix"" } }, { ""description.lower"": {""contains"": ""patreon"" } }, { ""description.lower"": { ""contains"": ""pycharm"" } }, { ""description.lower"": { ""contains"": ""github"" } }, { ""description.lower"": { ""contains"": ""chatgpt"" } }, { ""tags.split_comma"": { ""in_csv"": ""Spotify"" } } ]",2025-01-22 00:40:10,Editable Built-in
Online orders,"[{""id"": {""in"": ""TLREVOGBP-d20200821t110751-an22000-iMOCKb4a9df5a-a320-40ce-85df-89c51506904a""}}, {""description.lower"": {""contains"": ""paypal""}, ""tags"": {""not_contains"": ""Therapy""}}, {""description.upper"": {""contains"": ""WWW.HP.COM""}}, {""description.lower"": {""contains"": ""amazon""}}, {""description.lower"": {""contains"": ""amznmktplace""}}, {""description.lower"": {""contains"": ""ebay""}}, {""description.lower"": {""contains"": ""asos""}}, {""description.lower"": {""contains"": ""samsung""}}]",2025-01-22 00:40:10,Editable Built-in
Entertainment,"[{""description.lower"": {""contains"": ""category: entertainment""}}]",2025-02-03 23:17:06,Editable Built-in
Currency exchange,"[{""description.lower"":{""contains"":""exchange""},""tags.split_comma"":{""in_csv"":""Revolut""}}]",2025-01-22 00:40:10,Editable Built-in
Other bills,"[{""description.lower"": {""contains"": ""jetbrains""}}, {""description.lower"": {""contains"": ""cosmote""}}, {""tags.lower"": {""contains"": ""spotify""}}, {""tags.lower"": {""contains"": ""giffgaff""}}, {""tags"": {""contains"": ""Therapy""}}, {""description.lower"": {""contains"": ""vision express""}}]",2025-01-22 00:40:10,Editable Built-in
Food,"[{""tags.split_comma"": {""in_csv"": ""Eating out""}}, {""tags.split_comma"": {""in_csv"": ""Super Market""}}, {""tags"": {""contains"": ""Food delivery""}}, {""tags"": {""contains"": ""Too good to go""}}]",2025-01-22 00:40:10,Editable Built-in
Transfers,"[{""tags.split_comma"":{""in_csv"":""My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent""}},{""description.upper"":{""contains"":""TYPE: TRANSFER""},""tags"":{""contains"":""Revolut""}}]",2025-01-22 00:40:10,Editable Built-in
Holiday Accommodation,"[{""description.lower"":{""contains"":""hotel""},""amount.abs"":{""greater"":30}},{""description.lower"":{""contains"":""hostel""},""amount.abs"":{""greater"":30}},{""tags"":{""contains"":""Rent""}},{""tags"":{""contains"":""Airbnb""}}]",2025-01-22 00:40:10,Editable Built-in
Holiday Transfer,"[{""tags"":{""contains"":""Flight tickets""}}]",2025-01-22 00:40:10,Editable Built-in
Home Bills,"[{""description.lower"": {""contains_phrase"": ""bt group plc""}}, {""description.lower"": {""contains_phrase"": ""aimee lawlor""}}, {""description.lower"": {""contains"": ""home bills""}, ""id"": {""not_contains"": ""TLREVOGBP-d20250727t110051-an3500-ife66537212b4863fc36b285cb5c5a2bd""}}, {""description.lower"": {""contains"": ""grainger""}, ""amount"": {""greater"": -800}}, {""description.lower"": {""contains"": ""thames water""}}, {""description.lower"": {""contains"": ""exarchou""}}, {""description.lower"": {""contains"": ""sideris""}}, {""description.lower"": {""contains"": ""virgin media""}}, {""description.lower"": {""contains"": ""bulb energy""}}]",,Editable Built-in
Eating out,"[{""description.lower"": {""contains"": ""eating_out""}}, {""description.lower"": {""contains"": ""eating out""}}, {""id"": {""in"": ""TLREVOGBP-d20200824t164853-an3051-iMOCK1c626351-762c-4b1d-82d2-3b92edd7148c,TLREVOGBP-d20200824t110611-an2391-iMOCK412c8ad0-5c23-4a21-abce-d204ecb6e70c""}}, {""description.lower"": {""contains"": ""category: eating_out""}}, {""description.lower"": {""contains"": ""deli ""}}, {""description.lower"": {""contains"": ""pophams""}}, {""description.lower"": {""contains"": ""restaurant""}}, {""description.lower"": {""contains"": ""nando""}}, {""description.lower"": {""contains"": ""mcdonald""}}, {""description.lower"": {""contains"": ""kfc""}}]",,Editable Built-in
"""
editable_tags_df = pd.read_csv(StringIO(editable_tags_csv_str))


custom_tags_csv_str = """name,conditions_json,type,date_created,bucket,key
ITV Salary,"[{""description"":{""contains"":""ITV""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Spotify,"[{""description.lower"":{""contains"":""spotify""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
GiffGaff,"[{""description.lower"":{""contains"":""giffgaff""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Cosmote,"[{""description.lower"":{""contains"":""cosmote""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
BorisBike,"[{""description.lower"":{""contains"":""tfl cycle hire""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
TFL,"[{""description.lower"":{""contains"":""tfl"",""not_contains"":""netflix""},""tags"":{""not_contains"":""BorisBike""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Therapy,"[{""description.lower"":{""contains"":""paypal""},""datetime.str"":{""greater"":""2023-04-06""},""amount.abs"":{""greater"":34,""less"":38}},{""description.lower"":{""contains"":""paypal""},""datetime.str"":{""less"":""2023-04-07"",""greater"":""2021-01-01""},""amount.abs"":{""greater"":25,""less"":28}},{""description.lower"":{""contains"":""karamanos""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Food delivery,"[{""description.lower"":{""contains"":[""just"",""eat""]}},{""description.lower"":{""contains"":[""uber"",""eat""]}},{""description.lower"":{""contains"":""efood""}},{""description.lower"":{""contains"":""e food""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Airbnb,"[{""description.lower"":{""contains"":""airbnb""}},{""description.lower"":{""contains"":""booking""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Boat,"[{""description.lower"":{""contains"":""blue star ferries""}},{""description.lower"":{""contains"":""anek lines""}},{""description.lower"":{""contains"":""koinopraxia anek""}},{""description.lower"":{""contains"":""ferry""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Spending,"[{""tags"":{""not_contains"":""Income""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Alpha Bank,"[{""description.upper"": {""contains"": ""THE CURRENCY CLOUD LTD""}}, {""description"": {""contains"": ""To Dimitrios (Alpha) Kontzedakis""}}, {""description"": {""contains"": ""Kontzedakis""}, ""currency"": {""equal"": ""EUR""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
LimeBike,"[{""description.lower"":{""contains"":""lime""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Uber Taxi,"[{""description.lower"":{""contains"":""uber"",""not_contains"":""eat""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Friends transfers,"[{""description.lower"":{""contains"":""sakkadakis""}},{""description.lower"":{""contains"":""karimpidis""}},{""description.lower"":{""contains"":[""michail"",""theodorouleas""]}},{""description.lower"":{""contains"":[""michail"",""fragkiadakis""]}},{""description.lower"":{""contains"":""merieme katsani""}},{""description.lower"":{""contains"":""marsel katsani""}},{""description.lower"":{""contains"":""stefano di tommaso""}},{""description.lower"":{""contains"":""stefano di tommaso""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Clothing,"[{""description.lower"":{""contains"":""urban outfitters""}},{""description.lower"":{""contains"":""zara""}},{""description.lower"":{""contains"":""h&m""}},{""description.lower"":{""contains"":""asos""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Finallot Salary,"[{""description"": {""contains"": ""ANALITIKA ONE""}}, {""description"": {""contains"": ""HUMAN RIGHTS Salary""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Drinks,"[{""description.lower"": {""contains"": ""tavern""}}, {""description"": {""contains"": ""ud83cudf7a""}}, {""description.lower"": {""contains"": ""lexington""}}, {""description"": {""contains"": ""ud83cudf78""}}, {""description.lower"": {""contains"": ""duke""}}, {""description.lower"": {""contains"": ""arms""}}, {""description.lower"": {""contains"": ""brewpub""}}, {""description.lower"": {""contains"": ""rose pub""}}, {""description.lower"": {""contains"": ""dream bags""}}, {""description.lower"": {""contains"": ""shacklewell""}}]",Custom,2025-03-10 20:32:01,mecon,tags/custom_tags.csv
Club,"[{""description.upper"": {""contains"": ""RESIDENT ADVISOR""}}, {""description.upper"": {""contains"": ""ELECTRIC BRIXTON""}}, {""description.lower"": {""contains"": ""jazz""}}, {""description.lower"": {""contains"": ""jago""}}, {""description.lower"": {""contains"": ""110 pennington street""}}, {""description.upper"": {""contains"": ""VILLAGE UNDERGROUND""}}, {""description.upper"": {""contains"": ""VILLAGE 512""}}, {""description.lower"": {""contains"": ""egg london""}}, {""description.lower"": {""contains"": ""drumshed""}}, {""description.lower"": {""contains"": ""fold""}}, {""description.lower"": {""contains"": ""printworks""}}, {""description.lower"": {""contains"": ""fabric""}}]",Custom,2025-03-10 21:13:56,mecon,tags/custom_tags.csv
Too good to go,"[{""description.lower"": {""contains"": ""polu poke""}}, {""description.lower"": {""contains"": ""toogoodtog""}}, {""description.lower"": {""contains"": ""too good to go""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Trainline Salary,"[{""description"": {""contains"": ""TRAINLINE.COM LTD""}}]",Custom,2025-01-22 00:40:10,mecon,tags/custom_tags.csv
Deloitte Salary,"[{""description.upper"": {""contains"": ""DELOITTE LLP""}, ""amount"": {""greater"": 2000}}]",Custom,,mecon,tags/custom_tags.csv
Monzo Spending,"[{""description.lower"": {""contains"": ""bank:monzo-api,""}, ""amount"": {""less"": 0, ""greater"": -300}, ""datetime.str"": {""greater"": ""2023-01-01""}}]",Custom,,mecon,tags/custom_tags.csv
BrandNewUniqueTag42,[{}],Custom,,mecon,tags/custom_tags.csv
Monzo Deposits,"[{""description.lower"": {""contains"": [""bank:ob-hsbc,"", ""dimitrios kontzedamonzo""]}}, {}]",Custom,,mecon,tags/custom_tags.csv
Phone Device,"[{""id"": {""in_csv"": ""RVLT-d20260703t222615-an48162-i5d2234d8e1c34151731d970c5de585fe,RVLT-d20240518t172039-an40122-i500ae0a0782a8ca8bd209cb26947704b,RVLT-d20221108t200254-an25499-i8a9d90a6cb3f59e8f1600d16c749d52e,MZN-d20200207t175144-an11500-id.tx_00009rnlvSpjxX4f3EBk3d""}}, {}]",Custom,,mecon,tags/custom_tags.csv
PC Equipment,"[{""id"": {""in_csv"": ""MZN-d20230423t020257-an135558-id.tx_0000AUvZZaJBeCoTVBvuzJ,RVLT-d20260217t173444-an38798-i12ad43ecd3db242e68014b1b112b7972""}}, {}]",Custom,,mecon,tags/custom_tags.csv
Amazon Order,"[{""description.lower"": {""contains"": ""amznmktplace""}}, {""description.lower"": {""contains"": ""amazon""}}]",Custom,,mecon,tags/custom_tags.csv
Ebay Order,"[{""description.lower"": {""contains"": ""ebay""}}]",Custom,,mecon,tags/custom_tags.csv
Online Shopping,"[{""tags.split_comma"": {""in_csv"": ""Amazon Order,Ebay Order, Asos Order,Temu Order,Alibaba Order""}}, {}]",Custom,,mecon,tags/custom_tags.csv
Asos Order,"[{""description.lower"": {""contains"": ""asos""}}, {}]",Custom,,mecon,tags/custom_tags.csv
"""
custom_tags_df = pd.read_csv(StringIO(custom_tags_csv_str))

all_tags_df = pd.concat([basic_tags_df, editable_tags_df, custom_tags_df,])
